apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ikapp
 
  labels:
    app:  ikapp
spec:
  selector:
    matchLabels:
      app: ikapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ikapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  ikapp
        image:  12bk/i2bk
        
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: ikapp
  
spec:
  selector:
    app: MYAPP
  type: LoadBalancer
 
  ports:
  - name: ikapp
    
    port: 80
    targetPort: 80
   
